### ISSUE TITLE
[DataCap Application] <The Second Life> - <3D-printed>

### ISSUE THREAD

**Issue by AlterEgogo** [NDLABS-Leo/Allocator-Pathway-Enterprise-data#10]
### Version

1

### DataCap Applicant

The Second Life

### Project ID

004

### Data Owner Name

The Second Life

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://mp.weixin.qq.com/s/IMtL_m4sQAxqCmNWlw28Gw

### Social Media Handle

https://mp.weixin.qq.com/s/IMtL_m4sQAxqCmNWlw28Gw

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1elogksj3uzo6izct6ol4z6enocwxidgeriivfqi

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Second Life Universe Block is a digital hipster block with 3D printing and digital twins as the underlying technology, and a collection of 3D-printed real-life artefacts, 3D-printed coffee, and meta-universe experiences. Embrace the future, private ordering, self-realisation, and one-click construction of the second life of real human beings.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
For each 3D printed model, we need to take high-precision photos of the 360-degree panorama. The production photos for one model are up to tens of thousands of photos, and we will model the model in 3D. We need to store these photos, models and other data
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We currently store our data on our own work computers, and on servers in the server room. In the case of data from the computers we will transfer it over the network, and in the case of data from the server we can do hard drive mailing
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
-
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We have not previously stored on an IPFS network and the cost of storing on an IPFS network will make it much cheaper for us to do business.SP's information is something we are currently in contact with on an ongoing basis, and I will disclose it below in the request form.
```

### Please share a sample of the data

```text
You can check out the WeChat video number, the name of the account is "第二人生3D真人手办".
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03079511 HK；
f02327534 美国；
f02894855 中国；
f02826234 SG
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by NDLABS-Leo** [comment]
@AlterEgogo 
Thank you for your application, according to the rules of fil+, I need to review your application for a number of things, once approved will gradually provide Datacap for you to carry out data storage projects:

1、Please explain your relationship to the project you are applying for and how you can demonstrate that you can be held accountable for the project.
2、Please understand the significance of the project when applying for this channel, and explain the reason for your application.
3、Please make sure that you are aware of the principles of multi-region, multi-backup, retrievability and data authenticity for the project to proceed.
4、Whether the disclosed nodes will be followed up according to this list
5、I will ask you to store a small amount of data at the beginning of the project, so that we can retrieve the data on a sample basis.

**Comment by AlterEgogo** [comment]
@NDLABS-Leo 
Thank you for your prompt reply, I am the person in charge of the 3D printing project, the number left on our video number is my phone number, you can contact me by phone. The submission of this application is the result of thorough research within our company. We will also fully adhere to the IPFS storage guidelines. The nodes of storage will be followed up and disclosed by us on an ongoing basis. It is fully compliant with your request.

**Comment by NDLABS-Leo** [comment]
@AlterEgogo Okay, I'll be in touch with you by phone, so please take care.

**Comment by NDLABS-Leo** [comment]
@AlterEgogo Thank you for your co-operation, and as I said before, I will be making a small amount allocation to be used for.

**Comment by NDLABS-Leo** [comment]
@AlterEgogo Hi, is it possible to provide relevant KYB certificates? If it concerns private content, you can send the information to slack account: Leo - ND Labs.

**Comment by NDLABS-Leo** [comment]
@AlterEgogo Okay, please, we've been waiting for a long time, can we start normally?
Also, I have sent our business licence to your slack account, please check it out.

**Comment by AlterEgogo** [comment]
@NDLABS-Leo Okay, please, we've been waiting for a long time, can we start normally?
Also, I have sent our business licence to your slack account, please check it out

**Comment by NDLABS-Leo** [comment]
@AlterEgogo Thanks for the prompt response, have seen the document.

**Comment by NDLABS-Leo** [comment]
@AlterEgogo 
As required by community rules, I will delegate based on 50% of your weekly application volume. I hope you can follow the community rules below:
1、guarantee the decentralisation of nodes
2、Requirements for data backup
In view of your data is enterprise data, we will check the project data with you during the project, please cooperate with us!

**Comment by AlterEgogo** [comment]
@NDLABS-Leo 
Thank you, because the project may last longer, we will currently work with the following sp for the first batch: f02948413 f02826234 f02826123 f02956383

**Comment by NDLABS-Leo** [comment]
KYB Disclosure:
![image](https://github.com/NDLABS-Leo/Allocator-Pathway-Enterprise-data/assets/104019147/413f6425-b753-4fe1-9e28-342e8569ec9b)

**Comment by NDLABS-Leo** [comment]
I can't continue because the system is reporting an error, please resubmit an issue, I'll close this issue.

![image](https://github.com/NDLABS-Leo/Allocator-Pathway-Enterprise-data/assets/104019147/7ae148a2-8b7d-4fb7-848a-d39798520589)
