### ISSUE TITLE
[DataCap Application] Cell Painting Gallery

### ISSUE THREAD

**Issue by lijo76618** [NDLABS-Leo/Allocator-Pathway-Enterprise-data#19]
### Version

1

### DataCap Applicant

Broad Institute

### Project ID

United Kingdom

### Data Owner Name

Cell Painting Gallery

### Data Owner Country/Region

United Kingdom

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/cellpainting-gallery/

### Social Media Handle

https://registry.opendata.aws/cellpainting-gallery/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

200TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1mszlkae7cbvmygensdmhne5qa4pyazef6xseczy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Our team is a very pure development team, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Cell Painting Gallery is a collection of image datasets created using the Cell Painting assay. The images of cells are captured by microscopy imaging, and reveal the response of various labeled cell components to whatever treatments are tested, which can include genetic perturbations, chemicals or drugs, or different cell types. The datasets can be used for diverse applications in basic biology and pharmaceutical research, such as identifying disease-associated phenotypes, understanding disease mechanisms, and predicting a drug’s activity, toxicity, or mechanism of action (Chandrasekaran et al 2020). This collection is maintained by the Carpenter–Singh lab and the Cimini lab at the Broad Institute. A human-friendly listing of datasets, instructions for accessing them, and other documentation is at the corresponding GitHub page about the Gallery.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
Disclaimer: 
Due to un-answered issues around whether combined requests or duplicate requests can be used to apply LDN. This is a series of recent new open datasets never applied by anybody (aka calling dibs).

Description: 
The Cell Painting Gallery is a collection of image datasets created using the Cell Painting assay. The images of cells are captured by microscopy imaging, and reveal the response of various labeled cell components to whatever treatments are tested, which can include genetic perturbations, chemicals or drugs, or different cell types. 

s3://cellpainting-gallery
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03151449, Shenzhen, China           
f03151456, Shenzhen, China               
f03179570, Singapore       
f03179555, Singapore           
f03178077, Tokyo, Japan   
f03178144, Tokyo, Japan   
f03179572, US 
f03214937, US 
f03229932, South Korea
f03229933, South Korea
```

### How do you plan to make deals to your storage providers

Boost client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by NDLABS-Leo** [comment]
@lijo76618 
Hello, and thank you for submitting your application to our channel. However, our channel is currently only open to enterprises. If you’re working with public datasets, we recommend applying through a more suitable channel where such applications are better supported. Thank you!
